stages:
  - Lint
  - Test

before_script:
  - cp tests/test_definitions.txt skillbridge/client/definitions.txt

lint_36:
  stage: Lint
  image: python:3.6
  script:
    - pip install flake8 mypy
    - flake8
    - mypy --strict skillbridge --show-error-context

lint_37:
  stage: Lint
  image: python:3.7
  script:
    - pip install flake8 mypy
    - flake8
    - mypy --strict skillbridge --show-error-context

test_36:
  stage: Test
  image: python:3.6
  script:
    - pip install pytest pytest-cov hypothesis
    - python -c "from skillbridge import fast_parser; assert not fast_parser"
    - pytest .

test_36_gcc:
  stage: Test
  image: python:3.6
  script:
    - pip install pytest pytest-cov hypothesis
    - pip install -vvv -I --force-reinstall .
    - cd tests
    - python -c "from skillbridge import fast_parser; assert fast_parser"
    - pytest ..

test_37:
  stage: Test
  image: python:3.7
  script:
    - pip install pytest pytest-cov hypothesis
    - python -c "from skillbridge import fast_parser; assert not fast_parser"
    - pytest .
  coverage: '/TOTAL.*\s+(\d+%)$/'

test_37_gcc:
  stage: Test
  image: python:3.7
  script:
    - pip install pytest pytest-cov hypothesis
    - pip install -vvv -I --force-reinstall .
    - cd tests
    - python -c "from skillbridge import fast_parser; assert fast_parser"
    - pytest ..
