language: python
python:
- '3.6'
- '3.7'
before_install:
- pip install --upgrade --upgrade-strategy eager -r dev-requirements.txt
- pip install --upgrade --upgrade-strategy eager codecov
install:
- python setup.py build_ext --inplace -fv
script:
- cp tests/test_definitions.txt skillbridge/client/definitions.txt
- flake8
- pytest
after_success:
- codecov
- rm coverage.xml
- cd docs
- make html
- touch _build/html/.nojekyll
- cd ..
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    keep_history: true
    local_dir: docs/_build/html
    on:
      branch: master
      tags: true
      python: 3.7
  - provider: pypi
    user: unihd-cag
    password:
      secure: kWhGCDBxJzHZlnifk1xxpfwICqAv6jLjazxcHNwR+xU505VqI8XX20IqnLtS+ytG2YQ4XthfUzVYBK10QY89PI79ztQfsQaVaK9RscIKSwde05QBq5fh4KONR5qvllrZ8efDSjMx8QIE5RatOCZm+nqZ0oOTMBbSbetMBNSWFoKEfKatm4g07zxNcqmd2dem9EtjduL44spZhxqWMKpYxSgVTPvuKOVdietLjE0a208fziCcvZIdlG0SWiEtBjB0tlecejUUpstO2a5b5NV/Qzp5upw9SsLydO5Zu5jCQF1+TcPqnfk7K6wBRhmfVWmhtoKVUsLKTqBix8IEwZ6G+N8qMdci/CHW0IIYaXGH0e1kDNYlKkMucHr5GnzonzyDk2yb+mTC7NIW3zJAmB6wjAXhBbGZhgvlpNoLTztSoCancoF7fMlzTbXDveMXulK3DU3eqGT7C7tuXQRJOimnlOSxcQJxyfC8drg7/dwQ7D0FAkxbDobmRNdKmNcle+opBhp51ermjLYPHZ8LYi92ceR37ywoYCcl38O4+KtlUbTO2Bi34h7b6QRIFkzw9V33tEzBpsSs+8aoyY9xlF7JS08KX4uETgR90bwihdV2jU64U/Co31YIPjDM79xetNUHylGnkX7bVkLlnPXL6FzQ0IR0gEUiBv/MWWAsm0adMc8=
    on:
      branch: master
      tags: true
      python: 3.7
