language: python

python:
  - "3.6"
  - "3.7"

before_install:
  - pip install -r dev-requirements.txt
  - pip install codecov

install:
  - python setup.py build_ext --inplace -fv

script:
  - cp tests/test_definitions.txt skillbridge/client/definitions.txt
  - flake8
  - pytest

after_success:
  - codecov
  - cd docs
  - make html
  - touch _build/html/.nojekyll

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
  local_dir: docs/_build/html

